services:
  - type: cron
    name: cotacao-dolar-cron
    env: python
    schedule: "*/10 12-21 * * 1-5"  # A cada 5 minutos, de segunda a sexta, das 9h às 18h (São Paulo)
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TZ
        value: America/Sao_Paulo
      - key: PYTHONUNBUFFERED
        value: "1"
    # Configurações opcionais
    region: oregon  # ou virginia, frankfurt, singapore
    plan: starter   # starter é gratuito
