name: Cotação do Dólar

on:
  schedule:
    # Executa a cada 5 minutos nos dias úteis (segunda a sexta)
    - cron: '*/5 * * * 1-5'
  workflow_dispatch:  # Permite execução manual

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar o script
        run: python Projeto_dollar.py
