name: Cotação do Dólar

on:
  schedule:
    - cron: '*/5 11-20 * * 1-5'  # UTC equivalente a 08h–17h BRT
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Instalar dependências
        run: |
          pip install requests beautifulsoup4
      
      - name: Executar o script
        run: python Projeto_dollar.py
