name: Cotação do Dólar
on:
  schedule:
    - cron: '*/1 * * * 1-5'  # A cada 5 minutos em dias úteis
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Instalar dependências
        run: pip install requests
      
      - name: Executar o script
        env:
          ALPHA_VANTAGE_KEY: ${{ secrets.ALPHA_VANTAGE_KEY }}
        run: python Projeto_dollar.py
